#!/bin/bash
# remove-rust  2025-03-12

	cat << EOF

	Rust Removal Script:

	This PKGBUILD attempts to use Arch's latest 'linux' package kernel config as is.
	However, there may be issues using this config that may lead to failure of
	the kernel build. One issue has proven to be rust in the config...

	The 'remove-rust' script removes rust from the config file in this
	directory by deleting the following 3 lines if they exist:
	
	  CONFIG_RUST=y
	  CONFIG_RUSTC_VERSION_TEXT=\"rustc ....
	  CONFIG_BINDGEN_VERSION_TEXT=\"bindgen ....
	
	and replaces them with:
	
	  # CONFIG_RUST is not set

	This should be tried only when a first build attempt has failed.

EOF
	while read -n1 -srp "        Proceed? [y/n] " reply
	do
		if [[ ${reply} == y ]]; then echo ; break ; fi
	      { if [[ ${reply} == n ]]; then echo ; fi ; exit ; }
	done

if	grep -q 'CONFIG_RUST=y' config ; then

	printf '\n%s\n' "line#        The conf file before edits:"
	printf '%s\n' "-------------------------------------------------------------"

	awk '/^# end of Kernel Performance Events And Counters/,/^# Kexec and crash features/ {print NR, $0}' config

	printf '%s\n' "-------------------------------------------------------------" 

	sed -i 's/CONFIG_RUST=y/# CONFIG_RUST is not set/'	config
	sed -i '/^CONFIG_RUSTC_VERSION_TEXT.*/d'		config
	sed -i '/^CONFIG_BINDGEN_VERSION_TEXT.*/d'		config

	printf '\n\n%s\n' "line#        The conf file after edits:"
	printf '%s\n' "-------------------------------------------------------------"

	awk '/^# end of Kernel Performance Events And Counters/,/^# Kexec and crash features/ {print NR, $0}' config

	printf '%s\n' "-------------------------------------------------------------"

    else
	printf '\n%s\n\n' "        The config does not have 'CONFIG_RUST=y'. No edits made."
fi
	cat << EOF

	The kernel build system will make edits to the supplied config file as needed.
	You can grab this edited, optimized for your system config to use later.
	Keep in mind that it's optimized for this kernel only as well.
	It's located in the root directory of the kernel source as '.config'


	Will resume building linux-stable-rc in 5 seconds...

EOF
	sleep 5
